### ISSUE TITLE
Error Message : "Token 설정에 실패했습니다"

### ISSUE THREAD

**Issue by jihun-ko** [parksb/darim#8]
<img width="952" alt="스크린샷 2023-04-04 오후 8 40 37" src="https://user-images.githubusercontent.com/37041154/229780457-741ee131-5e93-4a9a-82ab-066b5c5cc631.png">

Sign up is not working 🤔

**Comment by parksb** [comment]
계정 인증 메일 발송에 실패하여 발생한 문제였습니다. 54da219f69c4178f4f89559cff15a9bd58b5e59e..e97e429f400e888d703512aebb55020d5ba364a9 에서 수정했습니다. 제보 감사합니다 :)

It was a problem caused by a failure to send an account verification mail. I fixed this issue in 54da219f69c4178f4f89559cff15a9bd58b5e59e..e97e429f400e888d703512aebb55020d5ba364a9. Thank you for the report :)
